SELECT ROW_NUMBER()OVER(PARTITION BY Covid.PatientID,Covid.PatientPK,Covid.SiteCode ORDER BY Covid19AssessmentDate Desc)AS RowNumber,
       cast (Covid.PatientID as nvarchar) As PatientID ,
       cast (Covid.PatientPK as nvarchar) As PatientPK,
       cast (Covid.SiteCode as nvarchar) As SiteCode,
       Covid.FacilityName,
       VisitID,
       Max (Covid19AssessmentDate)Covid19AssessmentDate ,
       ReceivedCOVID19Vaccine ,
       DateGivenFirstDose ,
       FirstDoseVaccineAdministered
        ,DateGivenSecondDose,
       SecondDoseVaccineAdministered ,
       VaccinationStatus ,
       VaccineVerification ,
       BoosterGiven ,
       BoosterDose ,
       BoosterDoseDate ,
       EverCOVID19Positive ,
       COVID19TestDate,
       PatientStatus ,
       AdmissionStatus ,
       AdmissionUnit ,
       MissedAppointmentDueToCOVID19 ,
       COVID19PositiveSinceLasVisit ,
       COVID19TestDateSinceLastVisit ,
       PatientStatusSinceLastVisit,
       AdmissionStatusSinceLastVisit,
       AdmissionStartDate,
       AdmissionEndDate,
       AdmissionUnitSinceLastVisit,
       SupplementalOxygenReceived,
       PatientVentilated,
       TracingFinalOutcome ,
       CauseOfDeath,
       datediff(yy, patient.DOB, last_encounter.LastEncounterDate) as AgeLastVisit
from ODS.dbo.CT_Covid as Covid
         left join ODS.dbo.CT_Patient as patient on patient.PatientPK = Covid.PatientPK and patient.SiteCode = Covid.SiteCode
         left join ODS.dbo.Intermediate_LastPatientEncounter as last_encounter on last_encounter.PatientPK = Covid.PatientPK and last_encounter.SiteCode = Covid.SiteCode
group by
    Covid.PatientID,
    Covid.PatientPK,
    PatientStatus,
    PatientStatusSinceLastVisit,
    Covid.SiteCode,
    Covid19AssessmentDate,
    Covid.FacilityName,
    VisitID,
    ReceivedCOVID19Vaccine,
    DateGivenFirstDose,
    FirstDoseVaccineAdministered,
    DateGivenSecondDose,
    SecondDoseVaccineAdministered,
    VaccinationStatus,
    VaccineVerification,
    BoosterGiven,
    BoosterDose,
    BoosterDoseDate,
    EverCOVID19Positive,
    COVID19TestDate,
    AdmissionStatus,
    AdmissionUnit,
    MissedAppointmentDueToCOVID19,
    COVID19PositiveSinceLasVisit,
    COVID19TestDateSinceLastVisit,
    AdmissionStatusSinceLastVisit,
    AdmissionStartDate,
    AdmissionEndDate,
    AdmissionUnitSinceLastVisit,
    SupplementalOxygenReceived,
    PatientVentilated,
    TracingFinalOutcome,
    CauseOfDeath,
    DOB,
    LastEncounterDate