select
    patient.PatientKey,
    facility.FacilityKey,
    partner.PartnerKey,
    agency.AgencyKey,
    EncounterId,
    VisitID,
    Department,
    IsHealthWorker,
    RelationshipWithContact,
    TestedHIVBefore,
    WhoPErformedTest,
    ResultOfHIV,
    StartedOnART,
    CCCNumber,
    EverHadSex,
    SexuallyActive,
    NewPartner,
    PartnerHIVStatus,
    CoupleDiscordant,
    MultiplePartners,
    NumberOfPartners,
    AlcoholSex,
    MoneySex,
    CondomBurst,
    UnknownStatusPartner,
    KnownStatusPartner,
    Pregnant,
    BreastfeedingMother,
    ExperiencedGBV,
    ContactWithTBCase,
    Lethargy,
    EverOnPrep,
    CurrentlyOnPep,
    EverHadSTI,
    CurrentlyHasSTI,
    EverHadTB,
    SharedNeedle,
    NeedleStickInjuries,
    TraditionalProcedures,
    ChildReasonsForIneligibility,
    EligibleForTest,
    ReasonsforIneligibility,
    specificReasonForIneligibility,
    Cough,
    DateTestedProvider.DateKey As DateTestedProviderKey,
    Fever,
    MothersStatus,
    NightSweats,
    ReferredForTesting,
    ResultOfHIVSelf,
    ScreenedTB,
    TBStatus,
    WeightLoss,
    AssessmentOutcome,
    ForcedSex,
    ReceivedServices,
    TypeGBV,
    VisitDate.DateKey As VisitDateKey,
    DateTestedSelf.DateKey as DateTestedSelfKey,
    current_date() as LoadDate
from source_data
    left join DimPatient as patient on patient.PatientPKHash = source_data.PatientPKHash
    and patient.SiteCode = source_data.SiteCode
    left join DimFacility as facility on facility.MFLCode = source_data.SiteCode
    left join MFL_partner_agency_combination on MFL_partner_agency_combination.MFL_Code = source_data.SiteCode
    left join DimPartner as partner on partner.PartnerName = MFL_partner_agency_combination.SDP
    left join DimAgency as agency on agency.AgencyName = MFL_partner_agency_combination.Agency
    left join DimDate as VisitDate on VisitDate.Date = source_data.VisitDate
    left join DimDate as DateTestedSelf on DateTestedSelf.Date = source_data.DateTestedSelf
    left join DimDate as DateTestedProvider on DateTestedProvider.Date = source_data.DateTestedProvider